# Grunt aliases
---
# Build everything
build:
  - 'build:js'
  - 'build:i18n'
# Build JavaScript from assets to production
'build:js':
  - 'uglify'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
  - 'makepot'
  - 'glotpress_download'

# Check health of the project
check:
  - 'check:js'
  - 'check:php'
  - 'check:i18n'
'check:js':
  - 'jshint'
  - 'jsonlint'
  - 'jsvalidate'
  - 'jscs'
'check:php':
  - 'phplint'
  - 'phpcs'
'check:i18n':
  - 'checktextdomain'
# Create a zipped artifact from a fresh build
'create:artifact':
  - 'update-version'
  - 'build'
  - 'copy:artifact'
  - 'compress:artifact'
# Copy the needed files to the ./artifact folder
'copy:artifact':
  - 'copy:artifactFiles'
# Create a compressed zip from the ./artifact folder
'compress:artifact':
  - 'compress:artifactFiles'
# Default task
default:
  - build
